apiVersion: batch/v1
kind: Job
metadata:
  name: main-api-load-test
  namespace: prod-api
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: load-test
    spec:
      restartPolicy: Never
      containers:
      - name: load-test
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            echo "Starting load test against main-api...";
            while true; do
              wget -q -T 2 -O- http://main-api/ > /dev/null
            done
